
OUTER_SET proficiency_bastardsword = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYBASTARDSWORD~)
OUTER_SET proficiency_longsword = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYLONGSWORD~)
OUTER_SET proficiency_shortsword = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYSHORTSWORD~)
OUTER_SET proficiency_axe = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYAXE~)
OUTER_SET proficiency_twohandedsword = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYTWOHANDEDSWORD~)
OUTER_SET proficiency_katana = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYKATANA~)
OUTER_SET proficiency_scimitar = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYSCIMITARWAKISASHININJATO~)
OUTER_SET proficiency_dagger = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYDAGGER~)
OUTER_SET proficiency_warhammer = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYWARHAMMER~)
OUTER_SET proficiency_spear = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYSPEAR~)
OUTER_SET proficiency_halberd = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYHALBERD~)
OUTER_SET proficiency_flail = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYFLAILMORNINGSTAR~)
OUTER_SET proficiency_mace = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYMACE~)
OUTER_SET proficiency_quarterstaff = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYQUARTERSTAFF~)
OUTER_SET proficiency_xbow = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYCROSSBOW~)
OUTER_SET proficiency_lbow = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYLONGBOW~)
OUTER_SET proficiency_sbow = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYSHORTBOW~)
OUTER_SET proficiency_dart = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYDART~)
OUTER_SET proficiency_sling = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYSLING~)
OUTER_SET proficiency_club = IDS_OF_SYMBOL (~STATS~ ~C0_PROFICIENCYCLUB~)

APPEND ~splprot.2da~ ~C0_PROFICIENCYBASTARDSWORD %proficiency_bastardsword% 1 1~ UNLESS ~C0_PROFICIENCYBASTARDSWORD %proficiency_bastardsword% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYBASTARDSWORD~ BEGIN
	    SET C0_PROFICIENCYBASTARDSWORD = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYLONGSWORD %proficiency_longsword% 1 1~ UNLESS ~C0_PROFICIENCYLONGSWORD %proficiency_longsword% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYLONGSWORD~ BEGIN
	    SET C0_PROFICIENCYLONGSWORD = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYSHORTSWORD %proficiency_shortsword% 1 1~ UNLESS ~C0_PROFICIENCYSHORTSWORD %proficiency_shortsword% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYSHORTSWORD~ BEGIN
	    SET C0_PROFICIENCYSHORTSWORD = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYAXE %proficiency_axe% 1 1~ UNLESS ~C0_PROFICIENCYAXE %proficiency_axe% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYAXE~ BEGIN
	    SET C0_PROFICIENCYAXE = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYTWOHANDEDSWORD %proficiency_twohandedsword% 1 1~ UNLESS ~C0_PROFICIENCYTWOHANDEDSWORD %proficiency_twohandedsword% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYTWOHANDEDSWORD~ BEGIN
	    SET C0_PROFICIENCYTWOHANDEDSWORD = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYKATANA %proficiency_katana% 1 1~ UNLESS ~C0_PROFICIENCYKATANA %proficiency_katana% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYKATANA~ BEGIN
	    SET C0_PROFICIENCYKATANA = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYSCIMITARWAKISASHININJATO %proficiency_scimitar% 1 1~ UNLESS ~C0_PROFICIENCYSCIMITARWAKISASHININJATO %proficiency_scimitar% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYSCIMITARWAKISASHININJATO~ BEGIN
	    SET C0_PROFICIENCYSCIMITARWAKISASHININJATO = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYDAGGER %proficiency_dagger% 1 1~ UNLESS ~C0_PROFICIENCYDAGGER %proficiency_dagger% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYDAGGER~ BEGIN
	    SET C0_PROFICIENCYDAGGER = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYWARHAMMER %proficiency_warhammer% 1 1~ UNLESS ~C0_PROFICIENCYWARHAMMER %proficiency_warhammer% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYWARHAMMER~ BEGIN
	    SET C0_PROFICIENCYWARHAMMER = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYSPEAR %proficiency_spear% 1 1~ UNLESS ~C0_PROFICIENCYSPEAR %proficiency_spear% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYSPEAR~ BEGIN
	    SET C0_PROFICIENCYSPEAR = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYHALBERD %proficiency_halberd% 1 1~ UNLESS ~C0_PROFICIENCYHALBERD %proficiency_halberd% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYHALBERD~ BEGIN
	    SET C0_PROFICIENCYHALBERD = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYFLAILMORNINGSTAR %proficiency_flail% 1 1~ UNLESS ~C0_PROFICIENCYFLAILMORNINGSTAR %proficiency_flail% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYFLAILMORNINGSTAR~ BEGIN
	    SET C0_PROFICIENCYFLAILMORNINGSTAR = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYMACE %proficiency_mace% 1 1~ UNLESS ~C0_PROFICIENCYMACE %proficiency_mace% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYMACE~ BEGIN
	    SET C0_PROFICIENCYMACE = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYQUARTERSTAFF %proficiency_quarterstaff% 1 1~ UNLESS ~C0_PROFICIENCYQUARTERSTAFF %proficiency_quarterstaff% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYQUARTERSTAFF~ BEGIN
	    SET C0_PROFICIENCYQUARTERSTAFF = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYCROSSBOW %proficiency_xbow% 1 1~ UNLESS ~C0_PROFICIENCYCROSSBOW %proficiency_xbow% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYCROSSBOW~ BEGIN
	    SET C0_PROFICIENCYCROSSBOW = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYLONGBOW %proficiency_lbow% 1 1~ UNLESS ~C0_PROFICIENCYLONGBOW %proficiency_lbow% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYLONGBOW~ BEGIN
	    SET C0_PROFICIENCYLONGBOW = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYSHORTBOW %proficiency_sbow% 1 1~ UNLESS ~C0_PROFICIENCYSHORTBOW %proficiency_sbow% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYSHORTBOW~ BEGIN
	    SET C0_PROFICIENCYSHORTBOW = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYDART %proficiency_dart% 1 1~ UNLESS ~C0_PROFICIENCYDART %proficiency_dart% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYDART~ BEGIN
	    SET C0_PROFICIENCYDART = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYSLING %proficiency_sling% 1 1~ UNLESS ~C0_PROFICIENCYSLING %proficiency_sling% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYSLING~ BEGIN
	    SET C0_PROFICIENCYSLING = %row%
	  END
	END
APPEND ~splprot.2da~ ~C0_PROFICIENCYCLUB %proficiency_club% 1 1~ UNLESS ~C0_PROFICIENCYCLUB %proficiency_club% 1 1~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PROFICIENCYCLUB~ BEGIN
	    SET C0_PROFICIENCYCLUB = %row%
	  END
	END

// CLASS PROFICIENCY CHECKS
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all item files
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
    READ_BYTE    0x1F fighter //reads the byte containing the fighter usability flag
    PATCH_IF ((fighter BAND 0b00001000) = 0b00000000) BEGIN 
      READ_BYTE    0x1E row1
      READ_BYTE    0x1F row2
      READ_BYTE    0x20 row3
      READ_BYTE    0x21 row4
      READ_SHORT    0x1C type //reads the byte containing item type
      READ_BYTE     0x31 proficiency // 0x32 is minimum Charisma, not part of proficiency
      PATCH_IF (proficiency = 89) AND (((row1 BAND 0b01000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b00110000) = 0b00000000) AND ((row4 BAND 0b00000000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                      ) BEGIN // bastard sword
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYBASTARDSWORD END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYBASTARDSWORD timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 90) AND (((row1 BAND 0b01000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b01110000) = 0b00000000) AND ((row4 BAND 0b00100000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                      ) BEGIN // longsword
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYLONGSWORD END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYLONGSWORD timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 91) AND (((row1 BAND 0b01000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b01110000) = 0b00000000) AND ((row4 BAND 0b00100000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                      ) BEGIN // short sword
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYSHORTSWORD END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYSHORTSWORD timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 92) AND (((row1 BAND 0b01000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b00110000) = 0b00000000) AND ((row4 BAND 0b00000000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // axe
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYAXE END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYAXE timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 93) AND (((row1 BAND 0b01000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b00110000) = 0b00000000) AND ((row4 BAND 0b00000000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // two handed sword
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYTWOHANDEDSWORD END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYTWOHANDEDSWORD timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 94) AND (((row1 BAND 0b01000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b01110000) = 0b00000000) AND ((row4 BAND 0b00100000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // katana
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYKATANA END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYKATANA timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 95) AND (((row1 BAND 0b01000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b01110000) = 0b00000000) AND ((row4 BAND 0b00100000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // scimitar
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYSCIMITARWAKISASHININJATO END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYSCIMITARWAKISASHININJATO timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 96) AND (((row1 BAND 0b01000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b01110100) = 0b00000000) AND ((row4 BAND 0b00100000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // dagger
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYDAGGER END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYDAGGER timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 97) AND (((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b00110000) = 0b00000000) AND ((row4 BAND 0b00000000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // warhammer
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYWARHAMMER END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYWARHAMMER timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 98) AND (((row1 BAND 0b01000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b00110000) = 0b00000000) AND ((row4 BAND 0b01000000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // spear
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYSPEAR END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYSPEAR timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 99) AND (((row1 BAND 0b01000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b00110000) = 0b00000000) AND ((row4 BAND 0b00000000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // halberd
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYHALBERD END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYHALBERD timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 100) AND (((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b00110000) = 0b00000000) AND ((row4 BAND 0b00000000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // flail
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYFLAILMORNINGSTAR END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYFLAILMORNINGSTAR timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 101) AND (((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b00110000) = 0b00000000) AND ((row4 BAND 0b00000000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // mace
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYMACE END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYMACE timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 102) AND (((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b01110100) = 0b00000000) AND ((row4 BAND 0b01000000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // staff
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYQUARTERSTAFF END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYQUARTERSTAFF timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 103) AND (((row1 BAND 0b01000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b00110000) = 0b00000000) AND ((row4 BAND 0b00000000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // crossbow
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYCROSSBOW END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYCROSSBOW timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 104) AND (((row1 BAND 0b00000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b00110000) = 0b00000000) AND ((row4 BAND 0b00000000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // longbow
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYLONGBOW END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYLONGBOW timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 105) AND (((row1 BAND 0b01000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b01110000) = 0b00000000) AND ((row4 BAND 0b00000000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // shortbow
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYSHORTBOW END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYSHORTBOW timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 106) AND (((row1 BAND 0b01000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b01110100) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // dart
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYDART END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYDART timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 107) AND (((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b01110100) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // sling
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYSLING END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYSLING timing = 2 power = 3 END
      END
      PATCH_IF (proficiency = 115) AND (((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b01110000) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // club
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
        LPF DELETE_EFFECT INT_VAR match_opcode = 319 match_parameter2 = C0_PROFICIENCYCLUB END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 2 parameter1 = 0 parameter2 = C0_PROFICIENCYCLUB timing = 2 power = 3 END
      END
      PATCH_IF (type = 5) AND (((row1 BAND 0b01000000) = 0b00000000) AND ((row2 BAND 0b00001000) = 0b00000000) AND ((row3 BAND 0b01110000) = 0b00000000) AND ((row4 BAND 0b00000000) = 0b00000000) AND !(((row1 BAND 0b11000000) = 0b00000000) AND ((row2 BAND 0b11111111) = 0b00000000) AND ((row3 BAND 0b01111111) = 0b00000000) AND ((row4 BAND 0b01100000) = 0b00000000))
                                        ) BEGIN // if it is arrows
        WRITE_BYTE    0x1E (row1 BAND 0b00111111) 
        WRITE_BYTE    0x1F (row2 BAND 0b00000000)
        WRITE_BYTE    0x20 (row3 BAND 0b10000000)
        WRITE_BYTE    0x21 (row4 BAND 0b10111111)
      END
    PATCH_IF !(proficiency = 0) BEGIN
		LPF DELETE_EFFECT
			INT_VAR
				match_opcode = 319
				match_parameter1 = 11
				match_parameter2 = 5
		END
		LPF DELETE_EFFECT
			INT_VAR
				match_opcode = 319
        match_power = 0
				match_parameter1 = 21
				match_parameter2 = 5
		END
		END
    END
  END
BUT_ONLY

COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all item files
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
    READ_BYTE    0x20 thief //reads the byte containing the thief usability flag
    PATCH_IF ((thief BAND 0b01000000) = 0b00000000) BEGIN // if it is usable by thieves
      READ_BYTE    0x1F cthief //reads the byte containing cleric/thieves usability flag
      READ_SHORT    0x1C type //reads the byte containing item type
      PATCH_IF (type = 5) BEGIN // if it is arrows
        WRITE_BYTE    0x1F (thief BAND 0b11111101)  // makes usable by cleric/thieves
      END
    END
  END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
  LPF DELETE_EFFECT INT_VAR match_special = 99999 END

ACTION_DEFINE_ASSOCIATIVE_ARRAY	WEAPPROF_CLASS	BEGIN
	~MAGE~		=>	4
	~FIGHTER~		=>	5
	~CLERIC~		=>	6
  ~THIEF~ => 7
  ~BARD~ => 8
  ~PALADIN~ => 9
  ~DRUID~ => 10
  ~RANGER~ => 11
  ~FIGHTER_MAGE~ => 12
  ~FIGHTER_CLERIC~ => 13
  ~FIGHTER_THIEF~ => 14
  ~FIGHTER_MAGE_THIEF~ => 15
  ~MAGE_THIEF~ => 16
  ~CLERIC_MAGE~ => 17
  ~CLERIC_THIEF~ => 18
  ~FIGHTER_DRUID~ => 19
  ~FIGHTER_MAGE_CLERIC~ => 20
  ~CLERIC_RANGER~ => 21
  ~MONK~ => 51
  ~SHAMAN~ => 60
END
ACTION_PHP_EACH WEAPPROF_CLASS AS class => class_number BEGIN

ACTION_DEFINE_ASSOCIATIVE_ARRAY	WEAPPROF_WEAPONTYPE	BEGIN
	~BASTARDSWORD~		          =>	8
	~LONGSWORD~		              =>	9
	~SHORTSWORD~	              =>	10
	~AXE~	                      =>	11
	~TWOHANDEDSWORD~	          =>	12
	~KATANA~	                  =>	13
	~SCIMITARWAKISASHININJATO~  =>	14
	~DAGGER~	                  =>	15
	~WARHAMMER~                 =>	16
	~CLUB~	                    =>	17
	~SPEAR~	                    =>	18
	~HALBERD~	                  =>	19
	~FLAILMORNINGSTAR~	        =>	20
	~MACE~	                    =>	21
	~QUARTERSTAFF~	            =>	22
	~CROSSBOW~	                =>	23
	~LONGBOW~	                  =>	24
	~SHORTBOW~	                =>	25
	~DART~	                    =>	26
	~SLING~	                    =>	27
END
ACTION_PHP_EACH WEAPPROF_WEAPONTYPE AS weapon => weapon_number BEGIN
COPY_EXISTING ~weapprof.2da~  ~override~
  COUNT_2DA_COLS col_count
    READ_2DA_ENTRY ~%weapon_number%~ ~%class_number%~ col_count ~%weapon%_%class%~
      PATCH_IF (EVAL ~%weapon%_%class%~ > 0) BEGIN
        SET EVAL ~%weapon%_%class%_1~ = 1
      END ELSE BEGIN
        SET EVAL ~%weapon%_%class%_1~ = 0
      END
      
END

ACTION_IF (EVAL ~BASTARDSWORD_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#89 END
END
 
ACTION_IF (EVAL ~LONGSWORD_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#90 END
END
 
ACTION_IF (EVAL ~SHORTSWORD_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#91 END
END
 
ACTION_IF (EVAL ~AXE_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#92 END
END
 
ACTION_IF (EVAL ~TWOHANDEDSWORD_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#93 END
END
 
ACTION_IF (EVAL ~KATANA_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#94 END
END
 
ACTION_IF (EVAL ~SCIMITARWAKISASHININJATO_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#95 END
END
 
ACTION_IF (EVAL ~DAGGER_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#96 END
END
 
ACTION_IF (EVAL ~WARHAMMER_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#97 END
END
 
ACTION_IF (EVAL ~CLUB_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#115 END
END
 
ACTION_IF (EVAL ~SPEAR_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#98 END
END
 
ACTION_IF (EVAL ~HALBERD_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#99 END
END
 
ACTION_IF (EVAL ~FLAILMORNINGSTAR_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#100 END
END
 
ACTION_IF (EVAL ~MACE_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#101 END
END
 
ACTION_IF (EVAL ~QUARTERSTAFF_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#102 END
END
 
ACTION_IF (EVAL ~CROSSBOW_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#103 END
END
 
ACTION_IF (EVAL ~LONGBOW_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#104 END
END
 
ACTION_IF (EVAL ~SHORTBOW_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#105 END
END
 
ACTION_IF (EVAL ~DART_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#106 END
END
 
ACTION_IF (EVAL ~SLING_%class%_1~ = 1) THEN BEGIN
  COPY_EXISTING ~C0PR#CL.SPL~ ~OVERRIDE~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~%class%~) parameter2 = 105 special = 99999 STR_VAR resource = EVAL C0PR#107 END
END
 
END
